"""Tests for the repo-instructions reference checker."""

from __future__ import annotations

import json
import unittest
from pathlib import Path

import extension_fixtures as fx
from repo_support import ROOT, SKILLS, run_python, temp_dir


CHECKER = SKILLS / "repo-instructions" / "scripts" / "instruction_refs.py"


def check(testcase: unittest.TestCase, root: Path) -> tuple[int, dict]:
    result = run_python(CHECKER, str(root))
    testcase.assertIn(result.returncode, {0, 1}, result.stderr)
    return result.returncode, json.loads(result.stdout)


def by_text(report: dict) -> dict[str, dict]:
    return {item["text"]: item for item in report["references"]}


class InstructionReferenceTests(unittest.TestCase):
    def build(self) -> tuple[Path, Path]:
        root = temp_dir(self)
        marker = root.parent / "executed.marker"
        fx.write(root / "package.json", '{"scripts": {"test": "jest", "lint": "eslint ."}}\n')
        fx.write(root / "Makefile", "check:\n\techo ok\n")
        fx.write(root / "scripts" / "build.py", "print('x')\n")
        fx.write(root / "pnpm-lock.yaml", "lockfileVersion: 9\n")
        fx.write(root / "docs" / "guide.md", "# Guide\n")
        fx.write(root / "gen" / "api.ts", "// DO NOT EDIT: generated by protoc\nexport {}\n")
        fx.write(
            root / "AGENTS.md",
            "# Rules\n\nSee [the guide](docs/guide.md) and [missing](docs/missing.md).\n"
            "Edit `scripts/build.py`, never `gen/api.ts`.\n\n```sh\nnpm run test\nnpm run deploy\nmake check\n"
            f"make release\npython scripts/build.py\npython scripts/gone.py\npython -m unittest\n"
            f"touch {marker}\n```\n",
        )
        fx.write(root / "CLAUDE.md", "Read AGENTS.md.\n\n```sh\npytest -q\n```\n")
        fx.write(root / "services" / "api" / "AGENTS.md", "Use `handlers/` here.\n")
        return root, marker

    def test_references_are_checked_without_execution(self) -> None:
        root, marker = self.build()
        code, report = check(self, root)
        self.assertEqual(1, code)
        refs = by_text(report)
        expectations = {
            "docs/guide.md": "verified",
            "docs/missing.md": "failed",
            "scripts/build.py": "verified",
            "npm run test": "verified",
            "npm run deploy": "failed",
            "make check": "verified",
            "make release": "failed",
            "python scripts/build.py": "verified",
            "python scripts/gone.py": "failed",
            "python -m unittest": "verified",
        }
        for text, status in expectations.items():
            with self.subTest(text=text):
                self.assertEqual(status, refs[text]["status"], refs.get(text))
        self.assertFalse(marker.exists())
        self.assertFalse(report["executed"])

    def test_scopes_generated_files_and_contradictions_are_reported(self) -> None:
        root, _ = self.build()
        _, report = check(self, root)
        files = {item["path"]: item for item in report["instruction_files"]}
        self.assertEqual("services/api", files["services/api/AGENTS.md"]["scope"])
        self.assertEqual("Claude Code", files["CLAUDE.md"]["host"])
        self.assertEqual(["gen/api.ts"], report["generated_files"])
        categories = {item["category"] for item in report["possible_contradictions"]}
        self.assertIn("test", categories)
        self.assertIn("package-manager", categories)

    def test_shorthand_paths_are_not_checked_instead_of_failed(self) -> None:
        root = temp_dir(self)
        fx.write(root / "plugins" / "tool" / "skills" / "x.md", "x\n")
        fx.write(root / "AGENTS.md", "Author skills under `skills/`.\n")
        code, report = check(self, root)
        self.assertEqual(0, code)
        ref = by_text(report)["skills/"]
        self.assertEqual("not checked", ref["status"])
        self.assertIn("plugins/tool/skills", ref["reason"])

    def test_this_repository_instructions_resolve(self) -> None:
        code, report = check(self, ROOT)
        self.assertEqual(0, code, [item for item in report["references"] if item["status"] == "failed"])
        self.assertEqual({"AGENTS.md", "CLAUDE.md"}, {item["path"] for item in report["instruction_files"]})
        self.assertIn("docs/inventory.md", report["generated_files"])


if __name__ == "__main__":
    unittest.main()
